version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: warehouse
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
  warehouse:
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    restart: always